# PYTHON PROVIDE LIBRARY CALLED NUMPY FOR MUMERICAL COMPUTATION

## HERE I WILL DISCUSS SOME BASIC AND ADVANCED CONCEPT ON NUMPY LIB

#### LETS GET STARTED


NumPy arrays are basically just Python lists with added features.
We  can easily convert a Python list to a Numpy array using the np.array function

#### first we need to import all necessary python library 

In [1]:
import numpy as np
import pandas as pd


The code below is an example usage of np.array to create a 2-D matrix

In [3]:
arr = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)# here i manually cast the matrix data type as float
arr

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

NOTE:- When the elements of a NumPy array are mixed types, then the array's type will be upcast to the highest level type we can understand with code

In [4]:
arr = np.array([0, 0.1, 2])# here all  array data will casted to float 
arr

array([0. , 0.1, 2. ])

also we can cast our data through pre defined function astype()

In [6]:
s_arr = np.array([0, 1, 2])
print(s_arr.dtype)
s_arr = arr.astype(np.float32)
print(s_arr.dtype)

int32
float32


 suppose we don't wants in our array to contain a value at particular index then we can easily placehold it to NaN value using np.nan

In [7]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


##### To represent infinity in NumPy, we use the np.inf special value. We can also represent negative infinity with -np.inf.

In [9]:
print(np.inf > 1000000)

arr = np.array([np.inf, 8])
print(repr(arr))

arr = np.array([-np.inf, 9])
print(repr(arr))

True
array([inf,  8.])
array([-inf,   9.])


### now its time to perform some basic mathmetical operation and also creat modify numpy array

 NumPy provides an option to create ranged data arrays using np.arange. The function acts very similar to the range function in Python

In [10]:
s_arr = np.arange(8)
print(repr(arr))

s_arr = np.arange(5.1)
print(repr(s_arr))

s_arr = np.arange(-1, 4)
print(repr(s_arr))

s_arr = np.arange(-1.5, 4, 2)
print(repr(s_arr))

array([-inf,   9.])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


To specify the number of elements in the returned array, rather than the step size, we can use the np.linspace function.

In [12]:
arr = np.linspace(5, 11, num=4)# it will give 4 values between 5-11
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)# here endpoint decide that last value of range is not 11
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)# as we already know that dtype kyeword is used for manually cast the array data
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11])


#### Reshaping data

The function we use to reshape data in NumPy is np.reshape. It takes in an array and a new shape as required arguments

In [14]:
arr = np.arange(8)

print(repr(arr))

newshape_arr = np.reshape(arr, (2, 4))
print(repr(newshape_arr))
print('New shape: {}'.format(newshape_arr.shape))

newshape_arr = np.reshape(arr, (-1, 2, 2))
print(repr(newshape_arr))
print('New shape: {}'.format(newshape_arr.shape))

array([0, 1, 2, 3, 4, 5, 6, 7])
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


##### numpy provide flatten function to reshape the matrix in 1-D form

In [16]:
arr = np.arange(10)
arr = np.reshape(arr, (2, 5))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
arr shape: (2, 5)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
flattened shape: (10,)


##### Transposing

 ##### as name suggest transpose We can just transpose the data, using the np.transpose function

In [19]:
arr = np.arange(10)
arr = np.reshape(arr, (5, 2))
trans_data = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(trans_data))
print('transposed shape: {}'.format(trans_data.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
arr shape: (5, 2)
array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])
transposed shape: (2, 5)


##### Zeros and ones

##### some times we need to fill our matrix in binary formate numpy provide function np.zeros and np.ones 

In [20]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]])


###### If we want to create an array of 0's or 1's with the same shape as another array, we can use np.zeros_like and np.ones_like.

In [21]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr))) # all matrix data replace with zero

arr = np.array([[0., 1.], [1.2, 4.]]) # all matrix data replace with zero
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]])


##### One of the main purposes of NumPy is to perform multi-dimensional arithmetic

##### lets get started 

In [23]:
arr = np.array([[5, 6], [7, 8]])
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))

array([[6, 7],
       [8, 9]])
array([[3.8, 4.8],
       [5.8, 6.8]])
array([[10, 12],
       [14, 16]])
array([[2.5, 3. ],
       [3.5, 4. ]])
array([[2, 3],
       [3, 4]], dtype=int32)
array([[25, 36],
       [49, 64]], dtype=int32)
array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])


### as i mentioned earlier that numpy provide huge function for mathmatical calculation some of them are used here

#The function np.exp performs a base e exponential on an array
#function np.exp2 performs a base 2 exponential
#np.log, np.log2, and np.log10 all perform logarithms on an input array

In [24]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Normal logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


###### we use np.power to calculate the power for any any base we can pass argument for base 

In [25]:
arr = np.array([[1, 2], [3, 4]])
#  3 to power of each number in arr
print(repr(np.power(3, arr)))
arr2 = np.array([[10.2, 4], [3, 5]])
#  arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

array([[ 3,  9],
       [27, 81]], dtype=int32)
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


#### function np.matmul which takes two vector/matrix arrays as input and produces a dot product or matrix multiplication

In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


#### In numpy we can easily randomize array using np.random function

In [29]:
print(np.random.randint(6))
print(np.random.randint(7))
print(np.random.randint(5, high=6))# here high argument denote the maximum range of randimized data

random_arr = np.random.randint(-3, high=14,
                               size=(2, 2))# by default the minimum reage is 0 but here in -3 the minimum value in array is -3 
print(repr(random_arr))

2
5
5
array([[ 4, -2],
       [-3,  5]])


#### The np.random.shuffle function allows us to randomly shuffle an array

In [31]:
s_vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(s_vec)
print(repr(s_vec))
np.random.shuffle(s_vec)
print(repr(s_vec))

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.random.shuffle(matrix)# in matrix shuffling we notice that only the row data goes tobe shuffle
print(repr(matrix))

array([4, 5, 1, 2, 3])
array([3, 1, 2, 5, 4])
array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])


 #### np.random.uniform function we can eaisly perform uniform distributation  

In [36]:
print(np.random.uniform())
print(np.random.uniform(low=-1.5, high=2.2))# here low and high argument provide a range means all random values between given high low range
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low=-3.4, high=5.9,
                             size=(2, 2))))

0.2171502363272113
0.8039699113721701
array([0.06103733, 0.73600159, 0.66255733])
array([[ 3.9681001 , -0.50160838],
       [ 1.04485702,  2.29623455]])


In [38]:
# we can also use np.random.normal  function to calculate normal (Gaussian) distribution.
print(np.random.normal())
print(np.random.normal(loc=1.5, scale=3.5))# The loc and scale represent the mean and standard deviation
print(repr(np.random.normal(loc=-2.4, scale=4.0,
                            size=(2, 2))))

0.27259592501757735
3.7228537333548406
array([[-4.48635092, -2.42492798],
       [-3.10896948,  6.09144915]])


#### we can also used np.random.choice to create customize distributation 

In [40]:
colors = ['teacher', 'student', 'hod']
print(np.random.choice(colors))

teacher


### i think its all about numpy basic concept 
###       saurabh dubey